### ISSUE TITLE
Missing rationale

### ISSUE THREAD

**Issue by glennsl** [plow-technologies/bs-aeson#2]
Hi. Going by jest the readme (without looking too hard at the changelog, admittedly) this seems like not much more than a copy of bs-json. Do you think you could add a bit of rationale and an example showcasing how this is different and "better"?

Also see https://redex.github.io/publish/ for general tips on documentation and metadata. I have it on hold for publishing on redex until this is addressed.

Thanks! :)

**Comment by mchaver** [comment]
Hey @glennsl , the readme examples are probably out of date, but the changelog should make it a bit clearer. I'll add the rationale soon.

This is definitely a fork of bs-json and different from bs-json and intends to "better" in the case that you want to interface BS/Reason with a Haskell backend that uses the aeson library for serialization. Serializations provided by this library should match the way Haskell aeson does serialization and also provide a number of types and functions that help interact with JSON serializations coming from Haskell. It may become large if necessary to match aeson. 

Also I have a project that automates some code from Haskell to BS that uses this library. However, feel free to repurpose any serializations you see here that might be useful in bs-json.

**Comment by glennsl** [comment]
Cool, Thanks for explaining! Let me know when you've updated the readme so I can list it on redex.
